name: copolymer-afe
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - pip:
    - joblib
    - matplotlib
    - seaborn

# If you plan to use the DNN (TensorFlow) uncomment the next line and install with conda or pip
# - tensorflow
